server.port=${SERVER_PORT:8082}
spring.application.name=catalog-service

# PostgreSQL datasource
spring.datasource.url=jdbc:postgresql://${CATALOG_DB_HOST:127.0.0.1}:${CATALOG_DB_PORT:5432}/${CATALOG_DB_NAME:catalog_db}
spring.datasource.username=${CATALOG_DB_USERNAME:${DB_USERNAME:postgres}}
spring.datasource.password=${CATALOG_DB_PASSWORD:${DB_PASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=false
