apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: cake-delight
  labels:
    app.kubernetes.io/name: api-gateway
    app.kubernetes.io/part-of: cake-delight
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: api-gateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: api-gateway
        app.kubernetes.io/part-of: cake-delight
    spec:
      enableServiceLinks: false
      containers:
        - name: api-gateway
          image: akashgupta2233/cake-delight-api-gateway:v1.0.1
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - configMapRef:
                name: gateway-routing-hosts
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 40
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
