apiVersion: v1
kind: Service
metadata:
  name: catalog-db
  namespace: cake-delight
  labels:
    app.kubernetes.io/name: catalog-db
    app.kubernetes.io/part-of: cake-delight
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: catalog-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
