apiVersion: v1
kind: ConfigMap
metadata:
  name: database-hosts
  namespace: cake-delight
  labels:
    app.kubernetes.io/part-of: cake-delight
data:
  CATALOG_DB_HOST: catalog-db
  ORDER_DB_HOST: order-db
  RATING_DB_HOST: rating-db
  NOTIFICATION_DB_HOST: notification-db
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rabbitmq-host
  namespace: cake-delight
  labels:
    app.kubernetes.io/part-of: cake-delight
data:
  RABBITMQ_HOST: rabbitmq
  RABBITMQ_PORT: "5672"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: service-hosts
  namespace: cake-delight
  labels:
    app.kubernetes.io/part-of: cake-delight
data:
  API_GATEWAY_HOST: api-gateway
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-routing-hosts
  namespace: cake-delight
  labels:
    app.kubernetes.io/part-of: cake-delight
data:
  CATALOG_SERVICE_HOST: catalog-service
  ORDER_SERVICE_HOST: order-service
  RATING_SERVICE_HOST: rating-service
  NOTIFICATION_SERVICE_HOST: notification-service
