apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rating-db-pvc
  namespace: cake-delight
  labels:
    app.kubernetes.io/name: rating-db
    app.kubernetes.io/part-of: cake-delight
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
