apiVersion: v1
kind: Secret
metadata:
  name: database-credentials
  namespace: cake-delight
  labels:
    app.kubernetes.io/part-of: cake-delight
type: Opaque
stringData:
  DB_USERNAME: cake-delight
  DB_PASSWORD: change-me-before-production
---
apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: cake-delight
  labels:
    app.kubernetes.io/part-of: cake-delight
type: Opaque
stringData:
  RABBITMQ_USERNAME: cake-delight
  RABBITMQ_PASSWORD: change-me-before-production
